### ISSUE TITLE
点子不错，希望改进

### ISSUE THREAD

**Issue by onexuan** [xujinyang/BiuEditText#1]
你的点子不错，图之前我也看到过，不过你把它做成安卓的控件，实在有点意外，希望改进的几点如下：
1、EditText 放在ScrollView中会出现定住不准
2、增加修改跳动文字的颜色设定函数
3、低版本兼容

**Comment by xujinyang** [comment]
谢谢建议，现在都一一添加了，请升级到1.2.0版本，欢迎继续issue
