### ISSUE TITLE
动画结束时位置endY不对

### ISSUE THREAD

**Issue by aboutZZ** [xujinyang/BiuEditText#2]
测试了一下，我的布局是一个`LinearLayout`,先是一个`TextView`,然后是文本框，不是在最上面，结果bug来了：字符动画结束时位置在文本框上面，立马觉得是`endY`的问题，于是用日志输出了`endY`的值，结果是0
根据你的`endY=baseline + ascent;`日志输出了`baseline`为29，而`ascent`为-29，结果endY....
![Uploading issu.jpg…]()

**Comment by xujinyang** [comment]
哈哈，不好意思，之前写的只是一个demo，兼容性的问题没有考虑，现在已经修复了
