### ISSUE TITLE
编译报错的问题

### ISSUE THREAD

**Issue by aolphn** [xujinyang/BiuEditText#9]
![ru rt vkzlb 9r g 7t_ki](https://cloud.githubusercontent.com/assets/9359883/19690366/279fd5be-9b03-11e6-9b77-ddebba72b78e.png)
我按照IDE的提示自己改好了，在我自己工厂的manifest里的Application标签下设置：tools:replace="android:label"。原因貌似是和jar包里的manifest里有冲突。

**Comment by xujinyang** [comment]
请升级到1.4.0,已经解决了这个问题，谢谢反馈
